WIFI_SSID = "WiFi-SSID"
WIFI_PASS = "WIFI_PASSWORD"

MQTT_BROKER = "broker.hivemq.com"
MQTT_PORT = 1883
MQTT_CLIENT_ID = "esp32-wol-client"
TOPIC_BASE = "remotewol/"

WOL_MAC = "AA:BB:CC:DD:EE:FF"
WOL_IP = "192.168.1.1"
WOL_PORT = 9

SECRET_KEY = "YOUR_LONG_COMPLEX_SECRET_KEY_HERE"

LED_PIN = 2
